version: "3.7"
name: lms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: Moomkenwe0909
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - lms-network

  redis:
    image: redis:alpine
    networks:
      - lms-network

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
      - .frappe:/home/frappe/
    #   - ./sites:/home/frappe/frappe-bench/sites
    #   - ./apps:/home/frappe/frappe-bench/apps
    #   - ./logs:/home/frappe/frappe-bench/logs
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - lms-network

volumes:
  mariadb-data:
  frappe:

networks:
  lms-network:
    driver: bridge
